### ISSUE TITLE
Fortsätt konfigurera should have cancel configuration as well

### ISSUE THREAD

**Issue by mwenell** [Webmie/App-and-Extension-2019#18]
PROBLEM

You cannot cancel VPN configuration if you come back long time later and do not wanna continue configurations.

SOLUTION

Cancel configurations button in modal

**Comment by Njugen** [comment]
We can add "Cancel" button on every configuration page in mobile webview (app data collection in android, vpn view, https opening view etc). What should happen if user clicks "Cancel" on any of these page?

We can
- Send the user to user profile, where all his/her projects are still listed

User is now in profile? What now? What if the user wants to continue configuration? Today, you have to restart the app/webview in order to get prompted about missing configs. Let's discuss more about this...

**Comment by Njugen** [comment]
A cancel button has now been added to all settings view (app data collection in android, vpn view, https opening view etc).

A full width banner now also shows up on top of the user profile if the webview detects user is using either ios or android AND any of the settings/configuration steps have been left unfinished, or if user has not visited the thank you-page. When this banner is clicked, user will be sent to the view where he can set the missing settings and fullfill the joining process.

Is this OK? Shall we change it or keep this as solution?
