### ISSUE TITLE
Chrome extension opens two pages after installation

### ISSUE THREAD

**Issue by mwenell** [Webmie/App-and-Extension-2019#45]
PROBLEM:

After Chrome extension (Survey browser) installation in Chrome Store it opens the "code" page from webview in Chrome store page same time it opens new tab and "code" page there as well.

SOLUTION:
1) Open only the code page in Chrome Store page/tab

2) Open the code page only in new tab

**Comment by Njugen** [comment]
**Why it happens:**
The number of tabs being opened corresponds to how many tabs has the join page's tab domain. This is because once the extension is installed, it looks for a join page tab to confirm that a joining process is ongoing.

Solution:
We remove the tab verification method. Instead of looking for tabs with join page domain, we should look for a cookie placed by the join page. If this cookie exists (which means the user is currently attempting to join a project), we open a new tab once extension is installed. This way, we guarantee that only one tab opens.

However, are we permitted to place a cookie in user's browser when he/she visits join page??

**Comment by Njugen** [comment]
Solution is now implemented in dev files. At next version update, the extension will use cookie instead of tabs.

**Comment by Njugen** [comment]
A solution has now been added. It works like this:

It loops through all tabs. If a tab actually exists, and its id is correct AND if url is identified as join page, then it runs update command on that tab and breaks the loop.

When update command is run:
Invitation code is read and inserted into the extension. Once the code entrance page is opened, the code will be prefilled and user may continue as usual.
