### ISSUE TITLE
[Webview][All Platforms] device_halted is still 0 in expired projects

### ISSUE THREAD

**Issue by Njugen** [Webmie/App-and-Extension-2019#72]
**Issue:**
A project, which the user has joined at any time, and which has a tracking period of 1 day still has not expired after the number of tracking period days has passed.

In for example this case, the device_halted returned by /membershiplist/ should be either 2 or 3, but the device_halted is still 0.

This is how it is supposed to work, right? If not, please explain and clarify by responding to this issue. 

**Why this is important:**
The device_halted plays a part in wether to show the project under either of the following headlines in the user profile:

- Recording Diaries (device_halted = 0)
- History of Diaries  (device_halted = 2 or 3, Or should I use "status" value instead???)
- Paused Diaries (device_halted = 1)

**Comment by majheikkila** [comment]
Device_halted value is used for configs and also reporting for client that is the device in active or pause state. Currently it is not changing when tracking period is over, but it's controlled otherwise when the device is not getting configurations anymore. For history, expired and enough/not enough data, you should use ["activity_status"]["code"] value.
